### ISSUE TITLE
android installation threat

### ISSUE THREAD

**Issue by bebeko89** [scala-network/MobileMiner#42]
after installing, my android detects it as threat and advices uninstall

**Comment by HydroxxOfficial** [comment]
[Malware??](https://www.virustotal.com/gui/file/182577aa1620a3af2c15eac52c2dbe76a846a430ce4fda37d5d4bc72eed16168/summary)  

😶😶😶

**Comment by hayzamjs** [comment]
All miners are usually classified as viruses since they're sometimes installed without the hardware owners permission(like in the case of botnets). The backend of this miner is XLArig, which itself is a fork of XMRig [here](https://www.virustotal.com/gui/file/d1d89ada2bd812473633d6aee4a4e1154affda7d0a5f8e3bf76638701b8c16f9/detection) is a scan of the latest version of xmrig.
